### ISSUE TITLE
Scala extension doesn't work

### ISSUE THREAD

**Issue by pedrozalexandro** [daltonjorge/vscode-scala#2]
Hi, just installed the extension with next config
Versión 1.7.1
Commit 02611b40b24c9df2726ad8b33f5ef5f67ac30b44
Date 2016-11-03T13:46:46.244Z
Shell 1.3.8
Representador 52.0.2743.82
Node 6.5.0
so: xubuntu 16.04 
extension installed from extensions search box

![virtualbox_xubu_19_11_2016_12_52_19](https://cloud.githubusercontent.com/assets/547785/20457779/2d9cfaf6-ae58-11e6-9220-da3b37bf6845.png)

**Comment by daltonjorge** [comment]
Hi Alejandro, can you update this extension and test again? Thank you.

**Comment by pedrozalexandro** [comment]
extension updated and reloaded, every is fine now. Thanks
![scalaok](https://cloud.githubusercontent.com/assets/547785/20572536/7a349f1a-b171-11e6-843b-4375fb3912e6.png)
