### ISSUE TITLE
go to definition not working

### ISSUE THREAD

**Issue by JonathanSchwob** [daltonjorge/vscode-scala#8]
* OSX 10.12.6
* VSCode Version 1.21.1 (1.21.1)
* Scala syntax (official) plugin 0.1.2
* reproduce issue: open scala/play framework project with vs code, install official scala plugin, try to cmd click a definition

When using VS Code on Scala projects 'Go To Definition' functionality does not work at all. I have installed this repos plugin. Nothing highlights when holding CMD. Nothing appears when I type 'Go To Definition' in the cmd pallete.

If i open a javascript project this functionality works perfectly and holding CMD highlights words and I can jump to their definitions in other files.

I'd really like to switch from IDEA to VScode for this project but this makes it difficult.

Is this intended? Thanks for your time, and please let me know if there are any additional details you might need from me.

**Comment by daltonjorge** [comment]
Hi @JonathanSchwob, thank you so much for your interest. 

The official Scala plugin is maintained here: [https://github.com/scala/vscode-scala-syntax](https://github.com/scala/vscode-scala-syntax).

The Scala group took my plugin as a base for the official plugin and I recommend you utilize it (and request new features in your repository, of course).

For the 'Go to definition' and other functionalities, you can use the [Scala Language Server](https://marketplace.visualstudio.com/items?itemName=dragos.scala-lsp). I've used it for a while and it's a great plugin!
