### ISSUE TITLE
Unpublish?

### ISSUE THREAD

**Issue by gabro** [daltonjorge/vscode-scala#9]
Hi @daltonjorge,
first of all thanks for this package, it's been super useful over these years.

Do you think it makes sense to unpublish it from the Marketplace, now that https://marketplace.visualstudio.com/items?itemName=scala-lang.scala exists?

I think it's kind of confusing for the users to find multiple identical plugins, one of which is marked as "Official".

Thanks

**Comment by daltonjorge** [comment]
Hi @gabro,
Yes, I'll unpublish my package. The Scala team created the official plugin and they are doing a great job.

Thanks

**Comment by gabro** [comment]
Thanks for the quick response!

**Comment by olafurpg** [comment]
@daltonjorge Could you please take a look at this again? It seems this extension is still published on the marketplace https://marketplace.visualstudio.com/items?itemName=daltonjorge.scala

The official Scala syntax extension has received several improvements over the past year and it is currently used by language server extensions like [Metals](https://marketplace.visualstudio.com/items?itemName=scalameta.metals) that provide completions.

**Comment by daltonjorge** [comment]
Hi @olafurpg, sorry for the long, long wait. I forgot this issue... =( 
I just removed my extension from the vs code marketplace.
Thanks for your warning.

**Comment by olafurpg** [comment]
@daltonjorge Thank you so much 🙏 I appreciate your help a lot!

**Comment by olafurpg** [comment]
@daltonjorge Thank you so much 🙏 I appreciate your help!
